# å½“å‰ç‰ˆæœ¬ | Theme Version
Hexo: "2.1"

#è¯­è¨€ | Language
# en | zh-Hans
#è¯·åœ¨hexoæ–‡ä»¶ä¸‹çš„"_config.yml"ä¿®æ”¹language
language: en

# ç½‘ç«™æ ‡é¢˜ | Title
logo_title: James ä¹¾è²¨ç´€éŒ„

# åˆå§‹åŒ–é£æ ¼ | Default Style "black/light"
style: black
#style: light

#SEOä¼˜åŒ–

## ç½‘ç«™æè¿°
description: Hi allï¼Œæˆ‘æœƒåœ¨é€™é‚Šæ”¾å¹³æ™‚é–‹ç™¼ç¢°åˆ°çš„é…·æ±è¥¿ æˆ–æ˜¯ programing å¿ƒå¾—ï¼Œèƒ½å¤ å¾é€™é‚Šæ‹¿åˆ°çŸ¥è­˜å°±æ‹¿å§ï¼

## ç½‘ç«™å…³é”®è¯ï¼šç”¨è‹±æ–‡é€—å·åˆ†å‰²
keywords: JamesHsueh,Coding, Programing, Devops, è–›è¯æ…¶

# é¦–é¡µURL | Your URL
link: https://codemachine0121.github.io

#æ ‡è¯­ | Your Slogan
words: é‚Šç©é‚Šå­¸ï¼Œå­¸æœƒäº†å†å¯«æ–‡ç« è¨˜éŒ„

# ä½ çš„æ˜µç§° | Your Name
author: James Hsueh åœ°ç„åˆ—è»Šè»Šé•·

# ä¸­å¿ƒå›¾æ ‡é€‰æ‹©ç”·å¥³æˆ–è€…è‡ªå®šä¹‰ | Gender
gender: /img/male.png #/img/female.png

# ç«™ç‚¹å°å›¾æ ‡åœ°å€ | Small Icon of Your Site
favicon: /img/favicon.ico

# èœå•æ é…ç½® | Nav Bar Settings
menu:
  LinkedinğŸ‘€: https://www.linkedin.com/in/%E8%8F%AF%E6%85%B6-%E8%96%9B-9a9178197/
  GitHubğŸ’: https://github.com/CodeMachine0121
  MediumğŸ“š: https://medium.com/@asdfg55887


# ç«™å†…å…³é”®è¯æœç´¢ | Local Search
search:
 enable: true
 path: search.xml
 field: post
 onload: true

# è¯„è®ºç³»ç»Ÿ | Comments
## åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
## è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalseâˆ‚
valine:
  enable: true
  appId:
  appKey:

# visitors count
counter:
  enable: true

highlight:
  enable: true
